---
- hosts: localhost
  vars_files: 
    - user_list.yml
  tasks: 

    - name: create users 
      vars: 
        password: "{{ lookup('password', 'filename-' + item.name + 'length=6 chars=digits') }}"
      ansible.builtin.user: 
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        state: present
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
        comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
      loop: "{{ users }}"
      
    - name: verify the created users
      ansible.builtin.command: "getent passwd {{ item.name }}"
      loop: "{{ users }}"
      register: user_info

    - name: display the user info
      debug: 
        var: user_info.results map(attribute='stdout') | list
