---
- name: creat users with GECOS
  hosts: all
  become: true
  vars_files:
    - user_info.yml

  tasks:
    - name: creat users with passwd
      loop: "{{ users }}"
      vars:
        password: "{{ lookup('password', 'filename-' + item.name, length=6, chars='digits') }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        update_password: on_create
        password: "{{ password | password_hash('sha512')}}"
        uid: "{{ item.uid }}"
        comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}" 


